### ISSUE TITLE
Glide example images not fetched using Delivery API

### ISSUE THREAD

**Issue by antstei** [flextype/docs.flextype.org#119]
**Describe the bug**
The Glide example images to demonstrate the following options

- Height
- Fit
- Device pixel ratio
- Brightness
- Contrast
- Gamma
- Sharpen
- Blur
- Pixelate
- Filter
- Border
- Quality
- Format

aren't fetched using the Delivery API for images and therefore not shown as expected.

**To Reproduce**
1. Navigate to [docs.flextype.org/en/content/media](http://docs.flextype.org/en/content/media)
2. Scroll down to 'A complete list of available options for Glide/Intervention
3. Click for instance on '[Height](http://docs.flextype.org/en/content/media/glide/height)'

**Expected behavior**
The respective example images are shown properly.

**Comment by Awilum** [comment]
not relevant
